-- Minimal initial schema for SQL Server (if not using EF migrations)
CREATE TABLE [Users] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [Email] NVARCHAR(200) NOT NULL UNIQUE,
  [FullName] NVARCHAR(200) NOT NULL,
  [PasswordHash] NVARCHAR(500) NOT NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE [Teams] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(200) NOT NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE [TeamUsers] (
  [TeamId] UNIQUEIDENTIFIER NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL,
  [Role] INT NOT NULL DEFAULT 1, -- 0=Admin,1=Member
  [JoinedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_TeamUsers PRIMARY KEY (TeamId, UserId),
  CONSTRAINT FK_TeamUsers_Teams FOREIGN KEY (TeamId) REFERENCES Teams(Id),
  CONSTRAINT FK_TeamUsers_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE [Tasks] (
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [Title] NVARCHAR(200) NOT NULL,
  [Description] NVARCHAR(MAX) NULL,
  [DueDate] DATETIME2 NULL,
  [Status] INT NOT NULL DEFAULT 0,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  [TeamId] UNIQUEIDENTIFIER NOT NULL,
  [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL,
  [AssignedToUserId] UNIQUEIDENTIFIER NULL,
  CONSTRAINT FK_Tasks_Teams FOREIGN KEY (TeamId) REFERENCES Teams(Id),
  CONSTRAINT FK_Tasks_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
  CONSTRAINT FK_Tasks_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id)
);
